modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "easierhydrogen"
version = "${mod_version}"
displayName = "Easier Hydrogen"
description = '''Adds easy Chemical Oxidizer recipes for Mekanism chemicals (hydrogen, oxygen, chlorine, sodium, ethene, sulfur dioxide, hydrofluoric acid, antimatter, plutonium, polonium, nuclear waste, fissile fuel, superheated sodium, steam, sulfur trioxide, sulfuric acid, spent nuclear waste, uranium oxide, uranium hexafluoride, water vapor, hydrogen chloride, clean metal slurries) plus, if Mekanism: Sun is installed, helium, an Alloyer uranium recipe, and iron-based electrum.'''

[[dependencies.easierhydrogen]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easierhydrogen]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easierhydrogen]]
modId = "mekanism"
type = "required"
versionRange = "[10.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.easierhydrogen]]
modId = "mekanismsun"
type = "optional"
versionRange = "[1.2,)"
ordering = "AFTER"
side = "BOTH"
